### ISSUE TITLE
Codes not Papers

### ISSUE THREAD

**Issue by zohaibcodes9642** [Marsrocky/Awesome-WiFi-CSI-Sensing#4]
Do you have the code for Human Activity Detection using Wifi CSI Data.
Where, Random Forest or TDNNs are used.?

no need for paper link please provide the actual model training code

**Comment by Marsrocky** [comment]
I assume you mean the benchmarking code for all the neural networks:
[[SenseFi Project]](https://github.com/xyanchen/WiFi-CSI-Sensing-Benchmark)

**Comment by zohaibcodes9642** [comment]
Yeah kindoff. will it work to train a model and create a .md file for it which can be used using restful apis?
